namespace: &namespace_anchor local

global:
  containers:
    dockerhub: "eosio"
    eosio:
      containerRepo: dockerhub
      containerTag: develop
    initContainer:
      containerRepo: dockerhub
      containerTag: develop
    pullPolicy: IfNotPresent
    nodeos:
      adminport: 31888
      histport: 30886
      p2pport: 30887
      nodeport: 30888
      testAccountsJson: minimal.json
  namespace: *namespace_anchor
  monitoring:
    namespace: monitoring
    enabled: false
  localLB: true
  pvsEnabled: false
  instance: *namespace_anchor
  branch: *namespace_anchor
  loadBalancerSourceRange: 0.0.0.0/0
  cloudProvider: *namespace_anchor
