global:
  containers:
    dockerhub: "eosio"
    eosio:
      containerRepo: dockerhub
      containerTag: develop
    initContainer:
      containerRepo: dockerhub
      containerTag: develop
    pullPolicy: IfNotPresent
    nodeos:
      adminport: 31888
      histport: 30886
      p2pport: 30887
      nodeport: 30888
      testAccountsJson: minimal.json
  namespace: local
  monitoring:
    namespace: monitoring
    enabled: false
  localLB: true
  pvsEnabled: false
  instance: local
  branch: local
  loadBalancerSourceRange: 0.0.0.0/0
  cloudProvider: local
