{{- $componentName := "nodeos" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.nodeosName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $componentName }}
    {{- if .Values.global.expires }}
    expires: {{ .Values.global.expiry }}
    {{- end }}

